/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package devfortress.utilities;

/**
 *
 * @author Cat Hoang Huy
 */
public enum Event {

    DEVELOPER_IS_SICK,
    REQUIREMENT_CHANGE,
    NEW_TECHNOLOGY,
    SOLUSTIONDOEST_NOT_SCALE,
    HACKED,
    FEATURE_CUT,
    BACKUP_FAIL,
    HOLIDAY,
    REDUNDANCIES,
    BONUS,
    TEAM_BUILDING_EXERCISE,
    EXPLORE_THE_EMPLOYEE_HAVING_TALENT,
    GET_SPONSOR_FOR_CURRENT_PROJECT,
    PROJECT_IS_STOLEN_BY_EMPLOYEE,
    EMPLOYEES_LEAVE_FOR_ANOTHER_COMPANY,
    INSPIRATION,
    DEVELOPER_HAS_BABY,
    TRAINING_SPONSOR,
    GOT_SUED_BY_ANOTHER_COMPANY,
    ACCIDENT_OCCURS_TO_EMPLOYEE,
    DEVELOPER_KILLS_ANOTHER_DEVELOPER,
    GOLDEN_EMPLOYEE,
    WAR_ERUPTS,
    COMPANY_IS_BURNT_DOWN_BY_ANONYMOUS,
    ZOMBIE_APOCALYPSE,}
