/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package devfortress.view.dialogs;

import devfortress.utilities.Constant;
import java.awt.event.ActionListener;

/**
 *
 * @author anhtran
 */
public class AboutPanel extends javax.swing.JPanel {

    /**
     * Creates new form AboutPanel
     */
    public AboutPanel(ActionListener buttonListener) {
        initComponents();
        btnClose.addActionListener(buttonListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitle = new javax.swing.JPanel();
        lblTiTle = new javax.swing.JLabel();
        pnlAuthor1 = new javax.swing.JPanel();
        lblAuthor1 = new javax.swing.JLabel();
        pnlAuthor2 = new javax.swing.JPanel();
        lblAuthor2 = new javax.swing.JLabel();
        pnlAuthor3 = new javax.swing.JPanel();
        lblAuthor3 = new javax.swing.JLabel();
        pnlCopyright = new javax.swing.JPanel();
        lblCopyright = new javax.swing.JLabel();
        pnlClose = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setMaximumSize(new java.awt.Dimension(600, 339));
        setMinimumSize(new java.awt.Dimension(600, 339));
        setPreferredSize(new java.awt.Dimension(600, 339));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        pnlTitle.setBackground(new java.awt.Color(255, 255, 255));
        pnlTitle.setMaximumSize(new java.awt.Dimension(560, 58));
        pnlTitle.setMinimumSize(new java.awt.Dimension(560, 58));
        pnlTitle.setName(""); // NOI18N
        pnlTitle.setPreferredSize(new java.awt.Dimension(560, 58));

        lblTiTle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTiTle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTiTle.setText(Constant.GAME);
        lblTiTle.setMaximumSize(new java.awt.Dimension(560, 28));
        lblTiTle.setMinimumSize(new java.awt.Dimension(560, 28));
        lblTiTle.setPreferredSize(new java.awt.Dimension(560, 28));

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTiTle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTiTle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        add(pnlTitle);

        pnlAuthor1.setBackground(new java.awt.Color(255, 255, 255));
        pnlAuthor1.setMaximumSize(new java.awt.Dimension(560, 42));
        pnlAuthor1.setMinimumSize(new java.awt.Dimension(560, 42));
        pnlAuthor1.setPreferredSize(new java.awt.Dimension(560, 42));

        lblAuthor1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblAuthor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAuthor1.setText(Constant.AUTHOR1);
        lblAuthor1.setMaximumSize(new java.awt.Dimension(560, 22));
        lblAuthor1.setMinimumSize(new java.awt.Dimension(560, 22));
        lblAuthor1.setPreferredSize(new java.awt.Dimension(560, 22));

        javax.swing.GroupLayout pnlAuthor1Layout = new javax.swing.GroupLayout(pnlAuthor1);
        pnlAuthor1.setLayout(pnlAuthor1Layout);
        pnlAuthor1Layout.setHorizontalGroup(
            pnlAuthor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAuthor1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAuthor1Layout.setVerticalGroup(
            pnlAuthor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAuthor1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblAuthor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlAuthor1);

        pnlAuthor2.setBackground(new java.awt.Color(255, 255, 255));
        pnlAuthor2.setMaximumSize(new java.awt.Dimension(560, 42));
        pnlAuthor2.setMinimumSize(new java.awt.Dimension(560, 42));
        pnlAuthor2.setPreferredSize(new java.awt.Dimension(560, 42));

        lblAuthor2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblAuthor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAuthor2.setText(Constant.AUTHOR2);
        lblAuthor2.setMaximumSize(new java.awt.Dimension(560, 22));
        lblAuthor2.setMinimumSize(new java.awt.Dimension(560, 22));
        lblAuthor2.setPreferredSize(new java.awt.Dimension(560, 22));

        javax.swing.GroupLayout pnlAuthor2Layout = new javax.swing.GroupLayout(pnlAuthor2);
        pnlAuthor2.setLayout(pnlAuthor2Layout);
        pnlAuthor2Layout.setHorizontalGroup(
            pnlAuthor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAuthor2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAuthor2Layout.setVerticalGroup(
            pnlAuthor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAuthor2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblAuthor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        add(pnlAuthor2);

        pnlAuthor3.setBackground(new java.awt.Color(255, 255, 255));
        pnlAuthor3.setMaximumSize(new java.awt.Dimension(560, 42));
        pnlAuthor3.setMinimumSize(new java.awt.Dimension(560, 42));
        pnlAuthor3.setPreferredSize(new java.awt.Dimension(560, 42));

        lblAuthor3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblAuthor3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAuthor3.setText(Constant.AUTHOR3);
        lblAuthor3.setMaximumSize(new java.awt.Dimension(560, 22));
        lblAuthor3.setMinimumSize(new java.awt.Dimension(560, 22));
        lblAuthor3.setPreferredSize(new java.awt.Dimension(560, 22));

        javax.swing.GroupLayout pnlAuthor3Layout = new javax.swing.GroupLayout(pnlAuthor3);
        pnlAuthor3.setLayout(pnlAuthor3Layout);
        pnlAuthor3Layout.setHorizontalGroup(
            pnlAuthor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAuthor3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAuthor3Layout.setVerticalGroup(
            pnlAuthor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAuthor3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblAuthor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        add(pnlAuthor3);

        pnlCopyright.setBackground(new java.awt.Color(255, 255, 255));
        pnlCopyright.setMaximumSize(new java.awt.Dimension(560, 37));
        pnlCopyright.setMinimumSize(new java.awt.Dimension(560, 37));
        pnlCopyright.setPreferredSize(new java.awt.Dimension(560, 37));

        lblCopyright.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCopyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCopyright.setText(Constant.COPYRIGHT);
        lblCopyright.setMaximumSize(new java.awt.Dimension(560, 17));
        lblCopyright.setMinimumSize(new java.awt.Dimension(560, 17));
        lblCopyright.setPreferredSize(new java.awt.Dimension(560, 17));

        javax.swing.GroupLayout pnlCopyrightLayout = new javax.swing.GroupLayout(pnlCopyright);
        pnlCopyright.setLayout(pnlCopyrightLayout);
        pnlCopyrightLayout.setHorizontalGroup(
            pnlCopyrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCopyright, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlCopyrightLayout.setVerticalGroup(
            pnlCopyrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCopyrightLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblCopyright, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlCopyright);

        pnlClose.setBackground(new java.awt.Color(255, 255, 255));
        pnlClose.setMaximumSize(new java.awt.Dimension(127, 78));
        pnlClose.setMinimumSize(new java.awt.Dimension(127, 78));
        pnlClose.setPreferredSize(new java.awt.Dimension(127, 78));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devfortress/view/resources/icCancel.png"))); // NOI18N
        btnClose.setText(Constant.CLOSE_BTN);
        btnClose.setMaximumSize(new java.awt.Dimension(127, 48));
        btnClose.setMinimumSize(new java.awt.Dimension(127, 48));
        btnClose.setPreferredSize(new java.awt.Dimension(127, 48));

        javax.swing.GroupLayout pnlCloseLayout = new javax.swing.GroupLayout(pnlClose);
        pnlClose.setLayout(pnlCloseLayout);
        pnlCloseLayout.setHorizontalGroup(
            pnlCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlCloseLayout.setVerticalGroup(
            pnlCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCloseLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(pnlClose);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel lblAuthor1;
    private javax.swing.JLabel lblAuthor2;
    private javax.swing.JLabel lblAuthor3;
    private javax.swing.JLabel lblCopyright;
    private javax.swing.JLabel lblTiTle;
    private javax.swing.JPanel pnlAuthor1;
    private javax.swing.JPanel pnlAuthor2;
    private javax.swing.JPanel pnlAuthor3;
    private javax.swing.JPanel pnlClose;
    private javax.swing.JPanel pnlCopyright;
    private javax.swing.JPanel pnlTitle;
    // End of variables declaration//GEN-END:variables
}
