/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package devfortress.view.dialogs;

import devfortress.model.employee.Employee;
import devfortress.view.editors.TableButtonCellEditor;
import devfortress.view.models.EmployeesTableModel;
import devfortress.view.renderers.TableButtonCellRenderer;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author Sherlock
 */
public class AllCurrentEmpolyees extends javax.swing.JPanel {

    /**
     * Creates new form AllCurrentEmpolyees
     */
    List<Employee> employeeList;
    public AllCurrentEmpolyees(List employeeList,ActionListener buttonListener) {
        this.employeeList = employeeList;
        initComponents();
        devListScroll.getViewport().setBackground(Color.white);
        employeeTable.setDefaultRenderer(JButton.class,
                new TableButtonCellRenderer());
        populateData();
    }
    
    /**
     * Set button listener for Employee table.
     *
     * @param tableButtonListener
     */
    
    public void setTableButtonListener(ActionListener tableButtonListener) {
        /* Set cell renderer for Employee table. */
        employeeTable.setDefaultEditor(JButton.class,
                new TableButtonCellEditor(tableButtonListener));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        devListScroll = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();

        employeeTable.setModel(new EmployeesTableModel());
        devListScroll.setViewportView(employeeTable);
        employeeTable.setRowHeight(36);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(devListScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(devListScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane devListScroll;
    private javax.swing.JTable employeeTable;
    // End of variables declaration//GEN-END:variables
    private void populateData() {
        /* Update Developers table. */
        EmployeesTableModel tblDevelopersModel =
                (EmployeesTableModel) employeeTable.getModel();
        tblDevelopersModel.setEmployeeList(employeeList);
    }
}
