/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package devfortress.view.dialogs;

import devfortress.model.employee.Employee;
import devfortress.model.facade.Model;
import devfortress.model.project.Project;
import devfortress.utilities.Constant;
import devfortress.utilities.Skill;
import devfortress.view.models.EmployeeTableModel;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author cathoanghuy
 */
public class AssignEmployeesPanel extends javax.swing.JPanel {

    private int index;
    private ProjectPanel parent;
    private Model model;
    private Project project;
    private Skill skill;
    private List<Employee> employeeList;
    private Employee currentEmployee;
    private EmployeeTableModel tableModel;
    private DecimalFormat decimalFormatter;

    /**
     * Creates new form AvaiableEmployee,
     *
     * @param employees
     * @param buttonListener
     */
    public AssignEmployeesPanel(JPanel parent, Model model, Project project,
            Skill skill, ActionListener buttonListener) {
        initComponents();
        scpEmployees.getViewport().setBackground(Color.white);
        tableModel = (EmployeeTableModel) tblEmployees.getModel();
        index = 0;
        this.parent = (ProjectPanel) parent;
        this.model = model;
        this.project = project;
        this.skill = skill;
        employeeList = model.getUnassignedEmployeeList();
        decimalFormatter = new DecimalFormat("$#,##0.0#");
        populateData();
        btnAssign.addActionListener(buttonListener);
        btnCancel.addActionListener(buttonListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlNameAndMainSkill = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblMainSkill = new javax.swing.JLabel();
        scpEmployees = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        pnlSalary = new javax.swing.JPanel();
        lblSalary = new javax.swing.JLabel();
        pnlPreviousNext = new javax.swing.JPanel();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        pnlAcceptCancel = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnAssign = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        setMaximumSize(new java.awt.Dimension(520, 520));
        setMinimumSize(new java.awt.Dimension(520, 520));
        setPreferredSize(new java.awt.Dimension(520, 520));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        pnlTitle.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText(Constant.ASSIGN);

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        lblTitle.getAccessibleContext().setAccessibleName("availableEmployee");

        add(pnlTitle);

        pnlNameAndMainSkill.setBackground(new java.awt.Color(255, 255, 255));

        lblName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblName.setText(Constant.EMPLOYEE_NAME);

        lblMainSkill.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMainSkill.setText(Constant.MAIN_SKILL_LABEL);

        javax.swing.GroupLayout pnlNameAndMainSkillLayout = new javax.swing.GroupLayout(pnlNameAndMainSkill);
        pnlNameAndMainSkill.setLayout(pnlNameAndMainSkillLayout);
        pnlNameAndMainSkillLayout.setHorizontalGroup(
            pnlNameAndMainSkillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNameAndMainSkillLayout.createSequentialGroup()
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(lblMainSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlNameAndMainSkillLayout.setVerticalGroup(
            pnlNameAndMainSkillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNameAndMainSkillLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlNameAndMainSkillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(lblMainSkill))
                .addGap(10, 10, 10))
        );

        add(pnlNameAndMainSkill);

        scpEmployees.setBackground(new java.awt.Color(255, 255, 255));
        scpEmployees.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        tblEmployees.setAutoCreateRowSorter(true);
        tblEmployees.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tblEmployees.setModel(new devfortress.view.models.EmployeeTableModel());
        tblEmployees.setRowHeight(36);
        tblEmployees.setRowSelectionAllowed(false);
        scpEmployees.setViewportView(tblEmployees);

        add(scpEmployees);

        pnlSalary.setBackground(new java.awt.Color(255, 255, 255));

        lblSalary.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSalary.setText(Constant.SALARY_LABEL);

        javax.swing.GroupLayout pnlSalaryLayout = new javax.swing.GroupLayout(pnlSalary);
        pnlSalary.setLayout(pnlSalaryLayout);
        pnlSalaryLayout.setHorizontalGroup(
            pnlSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        pnlSalaryLayout.setVerticalGroup(
            pnlSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSalaryLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblSalary)
                .addGap(10, 10, 10))
        );

        add(pnlSalary);

        pnlPreviousNext.setBackground(new java.awt.Color(255, 255, 255));
        pnlPreviousNext.setMaximumSize(new java.awt.Dimension(130, 60));
        pnlPreviousNext.setMinimumSize(new java.awt.Dimension(130, 60));
        pnlPreviousNext.setPreferredSize(new java.awt.Dimension(130, 60));

        btnPrevious.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devfortress/view/resources/icPrevious.png"))); // NOI18N
        btnPrevious.setMaximumSize(new java.awt.Dimension(40, 40));
        btnPrevious.setMinimumSize(new java.awt.Dimension(40, 40));
        btnPrevious.setPreferredSize(new java.awt.Dimension(40, 40));
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devfortress/view/resources/icNext.png"))); // NOI18N
        btnNext.setMaximumSize(new java.awt.Dimension(40, 40));
        btnNext.setMinimumSize(new java.awt.Dimension(40, 40));
        btnNext.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPreviousNextLayout = new javax.swing.GroupLayout(pnlPreviousNext);
        pnlPreviousNext.setLayout(pnlPreviousNextLayout);
        pnlPreviousNextLayout.setHorizontalGroup(
            pnlPreviousNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPreviousNextLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        pnlPreviousNextLayout.setVerticalGroup(
            pnlPreviousNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPreviousNextLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlPreviousNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        add(pnlPreviousNext);

        pnlAcceptCancel.setBackground(new java.awt.Color(255, 255, 255));

        btnCancel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devfortress/view/resources/icCancel.png"))); // NOI18N
        btnCancel.setText(Constant.CANCEL);
        btnCancel.setMaximumSize(new java.awt.Dimension(120, 40));
        btnCancel.setMinimumSize(new java.awt.Dimension(120, 40));
        btnCancel.setPreferredSize(new java.awt.Dimension(120, 40));

        btnAssign.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnAssign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devfortress/view/resources/icHire.png"))); // NOI18N
        btnAssign.setText(Constant.ASSIGN);
        btnAssign.setEnabled(false);
        btnAssign.setMaximumSize(new java.awt.Dimension(120, 40));
        btnAssign.setMinimumSize(new java.awt.Dimension(120, 40));
        btnAssign.setPreferredSize(new java.awt.Dimension(120, 40));

        javax.swing.GroupLayout pnlAcceptCancelLayout = new javax.swing.GroupLayout(pnlAcceptCancel);
        pnlAcceptCancel.setLayout(pnlAcceptCancelLayout);
        pnlAcceptCancelLayout.setHorizontalGroup(
            pnlAcceptCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcceptCancelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlAcceptCancelLayout.setVerticalGroup(
            pnlAcceptCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcceptCancelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAcceptCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        add(pnlAcceptCancel);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        if (index > 0) {
            btnNext.setEnabled(true);
            index--;
            if (index == 0) {
                btnPrevious.setEnabled(false);
            }
            populateData();
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (index < employeeList.size() - 1) {
            btnPrevious.setEnabled(true);
            index++;
            if (index == employeeList.size() - 1) {
                btnNext.setEnabled(false);
            }
            populateData();
        }
    }//GEN-LAST:event_btnNextActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JLabel lblMainSkill;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlAcceptCancel;
    private javax.swing.JPanel pnlNameAndMainSkill;
    private javax.swing.JPanel pnlPreviousNext;
    private javax.swing.JPanel pnlSalary;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JScrollPane scpEmployees;
    private javax.swing.JTable tblEmployees;
    // End of variables declaration//GEN-END:variables

    /**
     * Populate data to view.
     */
    private void populateData() {
        if (employeeList.size() > 0) {
            currentEmployee = employeeList.get(index);
            lblName.setText(String.format("%s: %s", Constant.EMPLOYEE_NAME,
                    currentEmployee.getName()));
            lblMainSkill.setText(String.format("%s: %s", Constant.MAIN_SKILL_LABEL,
                    currentEmployee.getMainSkill().toString()));
            lblSalary.setText(String.format("%s: %s", Constant.SALARY_LABEL,
                    decimalFormatter.format(currentEmployee.getSalary())));
            tableModel.setSkillList(currentEmployee.getSkillList());
            btnAssign.setActionCommand(String.valueOf(index));
            btnAssign.setEnabled(true);
        } else {
            lblName.setText(String.format("%s: %s", Constant.EMPLOYEE_NAME,
                    Constant.NA));
            lblMainSkill.setText(String.format("%s: %s", Constant.MAIN_SKILL_LABEL,
                    Constant.NA));
            lblSalary.setText(String.format("%s: %s", Constant.SALARY_LABEL,
                    Constant.NA));
            tableModel.setSkillList(null);
            btnAssign.setEnabled(false);
        }

        /* Update buttons' availability. */
        if (index > 0) {
            btnPrevious.setEnabled(true);
        } else {
            btnPrevious.setEnabled(false);
        }
        if (employeeList.size() < 2 || index == employeeList.size() - 1) {
            btnNext.setEnabled(false);
        } else {
            btnNext.setEnabled(true);
        }
    }

    /**
     * Assign current employee to specified project.
     */
    public void assign() {
        try {
            model.assignEmployeeToProject(currentEmployee, project, skill);
            parent.setProject(model.getProjectByName(project.getName()));
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(null, "EMPLOYEE IS BUSY RIGHT NOW", "ERROR", JOptionPane.OK_CANCEL_OPTION);
        }
    }
}
