/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package devfortress.view.dialogs;

import devfortress.model.Employee;
import devfortress.utilities.Constant;
import devfortress.utilities.Skill;
import devfortress.view.DevFortressView;
import devfortress.view.models.AvailableEmployeeTableModel;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author cathoanghuy
 */
public class AvailableEmployeePanel extends javax.swing.JPanel {

    private int index;
    private List<Employee> employeeList;
    private Employee currentEmployee;
    private AvailableEmployeeTableModel tableModel;

    /**
     * Creates new form AvaiableEmployee
     */
    public AvailableEmployeePanel(List employees) {
        initComponents();
        scpEmployees.getViewport().setBackground(Color.white);
        tableModel = (AvailableEmployeeTableModel) tblEmployees.getModel();
        index = 0;
        employeeList = employees;
        populateData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlNameAndMainSkill = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblMainSkill = new javax.swing.JLabel();
        scpEmployees = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        pnlSalary = new javax.swing.JPanel();
        lblSalary = new javax.swing.JLabel();
        pnlPreviousNext = new javax.swing.JPanel();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        pnlAcceptCancel = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        setPreferredSize(new java.awt.Dimension(300, 500));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        lblTitle.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblTitle.setText("Available Employee");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addContainerGap())
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblTitle.getAccessibleContext().setAccessibleName("availableEmployee");

        add(pnlTitle);

        lblName.setText("Name:");

        lblMainSkill.setText("Main Skill:");

        javax.swing.GroupLayout pnlNameAndMainSkillLayout = new javax.swing.GroupLayout(pnlNameAndMainSkill);
        pnlNameAndMainSkill.setLayout(pnlNameAndMainSkillLayout);
        pnlNameAndMainSkillLayout.setHorizontalGroup(
            pnlNameAndMainSkillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNameAndMainSkillLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                .addComponent(lblMainSkill)
                .addGap(45, 45, 45))
        );
        pnlNameAndMainSkillLayout.setVerticalGroup(
            pnlNameAndMainSkillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNameAndMainSkillLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNameAndMainSkillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(lblMainSkill))
                .addGap(38, 38, 38))
        );

        add(pnlNameAndMainSkill);

        scpEmployees.setBackground(new java.awt.Color(255, 255, 255));
        scpEmployees.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        tblEmployees.setAutoCreateRowSorter(true);
        tblEmployees.setModel(new AvailableEmployeeTableModel());
        scpEmployees.setViewportView(tblEmployees);

        add(scpEmployees);

        lblSalary.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSalary.setText(Constant.SALARY_LABEL);

        javax.swing.GroupLayout pnlSalaryLayout = new javax.swing.GroupLayout(pnlSalary);
        pnlSalary.setLayout(pnlSalaryLayout);
        pnlSalaryLayout.setHorizontalGroup(
            pnlSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSalaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSalary)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        pnlSalaryLayout.setVerticalGroup(
            pnlSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSalaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSalary)
                .addContainerGap())
        );

        add(pnlSalary);

        btnPrevious.setText(Constant.PREVIOUS_BTN);
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setText(Constant.NEXT_BTN);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPreviousNextLayout = new javax.swing.GroupLayout(pnlPreviousNext);
        pnlPreviousNext.setLayout(pnlPreviousNextLayout);
        pnlPreviousNextLayout.setHorizontalGroup(
            pnlPreviousNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPreviousNextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrevious)
                .addGap(71, 71, 71)
                .addComponent(btnNext)
                .addContainerGap())
        );
        pnlPreviousNextLayout.setVerticalGroup(
            pnlPreviousNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPreviousNextLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPreviousNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevious)
                    .addComponent(btnNext))
                .addContainerGap())
        );

        add(pnlPreviousNext);

        btnCancel.setText(Constant.CANCEL);

        btnAccept.setText(Constant.ACCEPT);

        javax.swing.GroupLayout pnlAcceptCancelLayout = new javax.swing.GroupLayout(pnlAcceptCancel);
        pnlAcceptCancel.setLayout(pnlAcceptCancelLayout);
        pnlAcceptCancelLayout.setHorizontalGroup(
            pnlAcceptCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcceptCancelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAccept)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addContainerGap())
        );
        pnlAcceptCancelLayout.setVerticalGroup(
            pnlAcceptCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcceptCancelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAcceptCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccept)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        add(pnlAcceptCancel);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        if (index > 0) {
            index--;
            populateData();
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (index < employeeList.size() - 1) {
            index++;
            populateData();
        }
    }//GEN-LAST:event_btnNextActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JLabel lblMainSkill;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlAcceptCancel;
    private javax.swing.JPanel pnlNameAndMainSkill;
    private javax.swing.JPanel pnlPreviousNext;
    private javax.swing.JPanel pnlSalary;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JScrollPane scpEmployees;
    private javax.swing.JTable tblEmployees;
    // End of variables declaration//GEN-END:variables

    /**
     * Populate data to view.
     */
    private void populateData() {
        currentEmployee = employeeList.get(index);
        lblName.setText(Constant.EMPLOYEE_NAME + ": " + currentEmployee.getName());
        lblMainSkill.setText(Constant.MAINSKILL_LABEL + ": "
                + currentEmployee.getMainSkill().toString());
        lblSalary.setText(Constant.SALARY_LABEL + ": " + currentEmployee.getSalary());
        tableModel.setSkillList(currentEmployee.getSkillList());
    }

    /**
     * Set listener for Accept and Cancel buttons.
     */
    public void setButtonListener(ActionListener buttonListener) {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException |
                IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(
                    DevFortressView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JFrame f = new JFrame();
                HashMap<Skill, Integer> skillList = new HashMap<>();
                skillList.put(Skill.C, 5);
                skillList.put(Skill.LISP, 4);
                skillList.put(Skill.DESIGN, 8);
                skillList.put(Skill.ALGORITHMS, 6);
                skillList.put(Skill.CONFIG_MANAGEMENT, 5);
                HashMap<Skill, Integer> skillList1 = new HashMap<>();
                skillList1.put(Skill.C, 9);
                skillList1.put(Skill.LISP, 3);
                skillList1.put(Skill.DESIGN, 5);
                skillList1.put(Skill.ALGORITHMS, 1);
                skillList1.put(Skill.CONFIG_MANAGEMENT, 7);
                HashMap<Skill, Integer> skillList2 = new HashMap<>();
                skillList2.put(Skill.C, 11);
                skillList2.put(Skill.LISP, 55);
                skillList2.put(Skill.DESIGN, 61);
                skillList2.put(Skill.ALGORITHMS, 61);
                skillList2.put(Skill.CONFIG_MANAGEMENT, 2);
                Employee e1 = new Employee("Joe", skillList),
                        e2 = new Employee("Doe", skillList1),
                        e3 = new Employee("Foo", skillList2);
                List<Employee> el = new ArrayList<>();
                el.add(e1);
                el.add(e2);
                el.add(e3);
                AvailableEmployeePanel p = new AvailableEmployeePanel(el);
                f.add(p);
                f.pack();
                f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                f.setVisible(true);
            }
        });
    }
}
