/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package devfortress.view.dialogs;

import devfortress.utilities.Constant;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Sherlock
 */
public class BuyItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form BuyItemPanel
     */
    private Icon pizzaImage, beerImage, comImage;

    public BuyItemPanel() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFood = new javax.swing.JPanel();
        noPizzaLbl = new javax.swing.JLabel();
        pizzaIncreaseBtn = new javax.swing.JButton();
        pizzaDecreaseBtn = new javax.swing.JButton();
        pnlBeer = new javax.swing.JPanel();
        beerIncreaseBtn = new javax.swing.JButton();
        noBeerLbl = new javax.swing.JLabel();
        beerDecreaseBtn = new javax.swing.JButton();
        pnlComputer = new javax.swing.JPanel();
        comIncreaseBtn = new javax.swing.JButton();
        comDecreaseBtn = new javax.swing.JButton();
        noComLbl = new javax.swing.JLabel();
        clearAllBtn = new javax.swing.JButton();
        Buy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        totalShoppingPrice = new javax.swing.JLabel();
        priceOfPizza = new javax.swing.JLabel();
        pizzaEqualSign = new javax.swing.JLabel();
        beerEqualSign = new javax.swing.JLabel();
        comEqualSign = new javax.swing.JLabel();
        priceOfBeer = new javax.swing.JLabel();
        priceOfCom = new javax.swing.JLabel();
        totalCostLbl = new javax.swing.JLabel();
        budgetLbl = new javax.swing.JLabel();
        totalCost = new javax.swing.JLabel();
        budget = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 700));

        pnlFood.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlFood.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout pnlFoodLayout = new javax.swing.GroupLayout(pnlFood);
        pnlFood.setLayout(pnlFoodLayout);
        pnlFoodLayout.setHorizontalGroup(
            pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        pnlFoodLayout.setVerticalGroup(
            pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        noPizzaLbl.setText("x");

        pizzaIncreaseBtn.setText(Constant.PLUS_SIGN);

        pizzaDecreaseBtn.setText(Constant.MINUS_SIGN);

        pnlBeer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlBeer.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout pnlBeerLayout = new javax.swing.GroupLayout(pnlBeer);
        pnlBeer.setLayout(pnlBeerLayout);
        pnlBeerLayout.setHorizontalGroup(
            pnlBeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        pnlBeerLayout.setVerticalGroup(
            pnlBeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        beerIncreaseBtn.setText(Constant.PLUS_SIGN);

        noBeerLbl.setText("x");

        beerDecreaseBtn.setText(Constant.MINUS_SIGN);

        pnlComputer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlComputer.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout pnlComputerLayout = new javax.swing.GroupLayout(pnlComputer);
        pnlComputer.setLayout(pnlComputerLayout);
        pnlComputerLayout.setHorizontalGroup(
            pnlComputerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        pnlComputerLayout.setVerticalGroup(
            pnlComputerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        comIncreaseBtn.setText(Constant.PLUS_SIGN);

        comDecreaseBtn.setText(Constant.MINUS_SIGN);

        noComLbl.setText("x");

        clearAllBtn.setText(Constant.CLEAR_BTN);

        Buy.setText(Constant.BUY_BTN);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(Constant.SHOP_LBL);

        totalShoppingPrice.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        totalShoppingPrice.setText(Constant.TOTAL);

        priceOfPizza.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        priceOfPizza.setText("jLabel2");

        pizzaEqualSign.setText(Constant.EQUAL_SIGN);

        beerEqualSign.setText(Constant.EQUAL_SIGN);

        comEqualSign.setText(Constant.EQUAL_SIGN);

        priceOfBeer.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        priceOfBeer.setText("jLabel2");

        priceOfCom.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        priceOfCom.setText("jLabel3");

        totalCostLbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        totalCostLbl.setText(Constant.TOTAL_COST_LBL);

        budgetLbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        budgetLbl.setText(Constant.BUDGET);

        totalCost.setText("jLabel2");

        budget.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(191, 191, 191)
                            .addComponent(totalShoppingPrice)
                            .addContainerGap(107, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(pnlBeer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(beerIncreaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(noBeerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(beerDecreaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(162, 162, 162)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(comEqualSign, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                .addComponent(beerEqualSign, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                .addComponent(pizzaEqualSign, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(pnlFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(noPizzaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(pizzaIncreaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                .addComponent(pizzaDecreaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(priceOfBeer)
                                        .addComponent(priceOfCom)
                                        .addComponent(priceOfPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addContainerGap(93, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlComputer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noComLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comIncreaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comDecreaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalCostLbl)
                                    .addComponent(budgetLbl)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(clearAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(budget)
                                    .addComponent(totalCost)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(totalShoppingPrice)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(pizzaIncreaseBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(noPizzaLbl)
                            .addComponent(priceOfPizza)
                            .addComponent(pizzaEqualSign))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pizzaDecreaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(pnlBeer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(beerIncreaseBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(noBeerLbl)
                            .addComponent(beerEqualSign)
                            .addComponent(priceOfBeer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(beerDecreaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlComputer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(comIncreaseBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(noComLbl)
                            .addComponent(comEqualSign)
                            .addComponent(priceOfCom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comDecreaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalCostLbl)
                    .addComponent(totalCost))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(budgetLbl)
                    .addComponent(budget))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buy;
    private javax.swing.JButton beerDecreaseBtn;
    private javax.swing.JLabel beerEqualSign;
    private javax.swing.JButton beerIncreaseBtn;
    private javax.swing.JLabel budget;
    private javax.swing.JLabel budgetLbl;
    private javax.swing.JButton clearAllBtn;
    private javax.swing.JButton comDecreaseBtn;
    private javax.swing.JLabel comEqualSign;
    private javax.swing.JButton comIncreaseBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel noBeerLbl;
    private javax.swing.JLabel noComLbl;
    private javax.swing.JLabel noPizzaLbl;
    private javax.swing.JButton pizzaDecreaseBtn;
    private javax.swing.JLabel pizzaEqualSign;
    private javax.swing.JButton pizzaIncreaseBtn;
    private javax.swing.JPanel pnlBeer;
    private javax.swing.JPanel pnlComputer;
    private javax.swing.JPanel pnlFood;
    private javax.swing.JLabel priceOfBeer;
    private javax.swing.JLabel priceOfCom;
    private javax.swing.JLabel priceOfPizza;
    private javax.swing.JLabel totalCost;
    private javax.swing.JLabel totalCostLbl;
    private javax.swing.JLabel totalShoppingPrice;
    // End of variables declaration//GEN-END:variables

    private void init() {
        pizzaImage = new ImageIcon("icBudget.png");
//          beerImage = ImageIO.read(new File("image name and path"));
//          comImage = ImageIO.read(new File("image name and path"));
//       } catch (IOException ex) {
        // handle exception...

        JLabel l = new JLabel();
        l.setIcon(pizzaImage);
        pnlFood.add(l);
    }
}
