/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package devfortress.view.dialogs;

import devfortress.model.facade.Model;
import devfortress.view.editors.TableButtonCellEditor;
import devfortress.view.models.EmployeesTableModel;
import devfortress.view.renderers.TableButtonCellRenderer;
import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Sherlock
 */
public class CurrentEmpolyees extends javax.swing.JPanel {

    private Model model;

    /**
     * Create current employees panel.
     *
     * @param employeeList
     * @param buttonListener
     */
    public CurrentEmpolyees(Model model, ActionListener buttonListener) {
        initComponents();
        this.model = model;
        scpEmployees.getViewport().setBackground(Color.white);
        tblEmployees.setDefaultRenderer(JButton.class,
                new TableButtonCellRenderer());
        populateData();
    }

    /**
     * Set button listener for Employee table.
     *
     * @param tableButtonListener
     */
    public void setTableButtonListener(ActionListener tableButtonListener) {
        /* Set cell renderer for Employee table. */
        tblEmployees.setDefaultEditor(JButton.class,
                new TableButtonCellEditor(tableButtonListener));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scpEmployees = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();

        tblEmployees.setAutoCreateRowSorter(true);
        tblEmployees.setModel(new EmployeesTableModel());
        scpEmployees.setViewportView(tblEmployees);
        tblEmployees.setRowHeight(36);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scpEmployees;
    private javax.swing.JTable tblEmployees;
    // End of variables declaration//GEN-END:variables

    /**
     * Populate data to table.
     *
     * @param model
     */
    private void populateData() {
        /* Update Developers table. */
        EmployeesTableModel tblDevelopersModel =
                (EmployeesTableModel) tblEmployees.getModel();
        tblDevelopersModel.setEmployeeList(model.getEmployeeList());
    }

    /**
     * Update current employees table.
     */
    public void update() {
        populateData();
    }
}
