/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package devfortress.view.dialogs;

import devfortress.model.employee.Employee;
import devfortress.utilities.Constant;
import devfortress.view.models.EmployeeTableModel;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import javax.swing.JPanel;

/**
 *
 * @author cathoanghuy
 */
public class EmployeePanel extends javax.swing.JPanel {

    private CurrentEmpolyees parent;
    private Employee employee;
    private EmployeeTableModel tableModel;
    private DecimalFormat decimalFormatter;

    /**
     * Creates new form EmployeeInformation
     */
    public EmployeePanel(JPanel parent, Employee employee,
            ActionListener buttonListener) {
        initComponents();
        scpSkills.getViewport().setBackground(Color.white);
        this.parent = (CurrentEmpolyees) parent;
        this.employee = employee;
        tableModel = (EmployeeTableModel) tblSkills.getModel();
        decimalFormatter = new DecimalFormat("$#,##0.0#");
        populateData();
        btnFire.addActionListener(buttonListener);
        btnFire.setActionCommand(employee.getName());
        btnCancel.addActionListener(buttonListener);
    }

    /**
     * Update employee list in the parent dialog.
     */
    public void updateEmployeeList() {
        parent.update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlNameAndMainSkill = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblMainSkill = new javax.swing.JLabel();
        scpSkills = new javax.swing.JScrollPane();
        tblSkills = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblSalary = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnFire = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setMaximumSize(new java.awt.Dimension(520, 520));
        setMinimumSize(new java.awt.Dimension(520, 520));
        setPreferredSize(new java.awt.Dimension(520, 520));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        pnlTitle.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText(Constant.EMPLOYEE_INFORMATION);

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTitle)
                .addGap(10, 10, 10))
        );

        add(pnlTitle);

        pnlNameAndMainSkill.setBackground(new java.awt.Color(255, 255, 255));

        lblName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblName.setText(Constant.EMPLOYEE_NAME);

        lblMainSkill.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMainSkill.setText(Constant.MAIN_SKILL_LABEL);

        javax.swing.GroupLayout pnlNameAndMainSkillLayout = new javax.swing.GroupLayout(pnlNameAndMainSkill);
        pnlNameAndMainSkill.setLayout(pnlNameAndMainSkillLayout);
        pnlNameAndMainSkillLayout.setHorizontalGroup(
            pnlNameAndMainSkillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNameAndMainSkillLayout.createSequentialGroup()
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(lblMainSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlNameAndMainSkillLayout.setVerticalGroup(
            pnlNameAndMainSkillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNameAndMainSkillLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlNameAndMainSkillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMainSkill)
                    .addComponent(lblName))
                .addGap(10, 10, 10))
        );

        add(pnlNameAndMainSkill);

        scpSkills.setBackground(new java.awt.Color(255, 255, 255));

        tblSkills.setAutoCreateRowSorter(true);
        tblSkills.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tblSkills.setModel(new EmployeeTableModel());
        tblSkills.setRowHeight(36);
        scpSkills.setViewportView(tblSkills);

        add(scpSkills);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblSalary.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSalary.setText(Constant.SALARY_LABEL);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblSalary)
                .addGap(10, 10, 10))
        );

        add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnCancel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devfortress/view/resources/icCancel.png"))); // NOI18N
        btnCancel.setText(Constant.CANCEL);
        btnCancel.setMaximumSize(new java.awt.Dimension(120, 40));
        btnCancel.setMinimumSize(new java.awt.Dimension(120, 40));
        btnCancel.setPreferredSize(new java.awt.Dimension(120, 40));

        btnFire.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnFire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devfortress/view/resources/icFire.png"))); // NOI18N
        btnFire.setText(Constant.BUTTON_FIRE);
        btnFire.setMaximumSize(new java.awt.Dimension(120, 40));
        btnFire.setMinimumSize(new java.awt.Dimension(120, 40));
        btnFire.setPreferredSize(new java.awt.Dimension(120, 40));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel4);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFire;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblMainSkill;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlNameAndMainSkill;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JScrollPane scpSkills;
    private javax.swing.JTable tblSkills;
    // End of variables declaration//GEN-END:variables

    /**
     * Populate data to view.
     */
    private void populateData() {
        lblName.setText(String.format("%s: %s", Constant.EMPLOYEE_NAME,
                employee.getName()));
        lblMainSkill.setText(String.format("%s: %s", Constant.MAIN_SKILL_LABEL,
                employee.getMainSkill().toString()));
        lblSalary.setText(String.format("%s: %s", Constant.SALARY_LABEL,
                decimalFormatter.format(employee.getSalary())));
        tableModel.setSkillList(employee.getSkillList());
    }
}
