/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package devfortress.view.dialogs;

import devfortress.model.employee.Employee;
import devfortress.model.facade.Model;
import devfortress.utilities.Constant;
import java.awt.event.ActionListener;
import javax.swing.JPanel;

/**
 *
 * @author Sherlock
 */
public class ManageEmployeePanel extends javax.swing.JPanel {

    private CurrentEmpolyees parent;
    private Employee employee;

    /**
     * Creates new form ManageEmployeePanel
     */
    public ManageEmployeePanel(JPanel parent, Employee employee,
            ActionListener buttonListener) {
        initComponents();
        this.parent = (CurrentEmpolyees) parent;
        this.employee = employee;
        btnGiveFood.addActionListener(buttonListener);
        btnGiveBeer.addActionListener(buttonListener);
        btnTrain.addActionListener(buttonListener);
        btnCancel.addActionListener(buttonListener);
    }

    /**
     * Get parent panel.
     *
     * @return
     */
    public JPanel getParentPanel() {
        return parent;
    }

    /**
     * Get game model.
     *
     * @return
     */
    public Model getModel() {
        return parent.getModel();
    }

    /**
     * Get current employee.
     *
     * @return
     */
    public Employee getEmployee() {
        return employee;
    }

    /**
     * Update parent panel.
     */
    public void update() {
        employee = parent.getModel().getEmployeeByName(employee.getName());
        parent.update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlGiveFood = new javax.swing.JPanel();
        btnGiveFood = new javax.swing.JButton();
        pnlHaveBeer = new javax.swing.JPanel();
        btnGiveBeer = new javax.swing.JButton();
        pnlTrain = new javax.swing.JPanel();
        btnTrain = new javax.swing.JButton();
        pnlCancel = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setMaximumSize(new java.awt.Dimension(300, 386));
        setMinimumSize(new java.awt.Dimension(300, 386));
        setPreferredSize(new java.awt.Dimension(300, 386));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        pnlTitle.setBackground(new java.awt.Color(255, 255, 255));
        pnlTitle.setMaximumSize(new java.awt.Dimension(260, 48));
        pnlTitle.setMinimumSize(new java.awt.Dimension(260, 48));
        pnlTitle.setPreferredSize(new java.awt.Dimension(260, 48));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText(Constant.EMPLOYEE_MANAGE);

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTitle)
                .addGap(10, 10, 10))
        );

        add(pnlTitle);

        pnlGiveFood.setBackground(new java.awt.Color(255, 255, 255));
        pnlGiveFood.setMaximumSize(new java.awt.Dimension(240, 80));
        pnlGiveFood.setMinimumSize(new java.awt.Dimension(240, 80));

        btnGiveFood.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnGiveFood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devfortress/view/resources/icGiveFood.png"))); // NOI18N
        btnGiveFood.setText(Constant.GIVE_FOOD_BTN);
        btnGiveFood.setMaximumSize(new java.awt.Dimension(240, 60));
        btnGiveFood.setMinimumSize(new java.awt.Dimension(240, 60));
        btnGiveFood.setPreferredSize(new java.awt.Dimension(240, 60));
        btnGiveFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiveFoodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGiveFoodLayout = new javax.swing.GroupLayout(pnlGiveFood);
        pnlGiveFood.setLayout(pnlGiveFoodLayout);
        pnlGiveFoodLayout.setHorizontalGroup(
            pnlGiveFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGiveFood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlGiveFoodLayout.setVerticalGroup(
            pnlGiveFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGiveFoodLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnGiveFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        add(pnlGiveFood);

        pnlHaveBeer.setBackground(new java.awt.Color(255, 255, 255));
        pnlHaveBeer.setMaximumSize(new java.awt.Dimension(240, 80));
        pnlHaveBeer.setMinimumSize(new java.awt.Dimension(240, 80));
        pnlHaveBeer.setPreferredSize(new java.awt.Dimension(240, 80));

        btnGiveBeer.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnGiveBeer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devfortress/view/resources/icGiveBeer.png"))); // NOI18N
        btnGiveBeer.setText(Constant.GIVE_BEER_BTN);
        btnGiveBeer.setMaximumSize(new java.awt.Dimension(240, 60));
        btnGiveBeer.setMinimumSize(new java.awt.Dimension(240, 60));
        btnGiveBeer.setPreferredSize(new java.awt.Dimension(240, 60));

        javax.swing.GroupLayout pnlHaveBeerLayout = new javax.swing.GroupLayout(pnlHaveBeer);
        pnlHaveBeer.setLayout(pnlHaveBeerLayout);
        pnlHaveBeerLayout.setHorizontalGroup(
            pnlHaveBeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGiveBeer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHaveBeerLayout.setVerticalGroup(
            pnlHaveBeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHaveBeerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnGiveBeer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        add(pnlHaveBeer);

        pnlTrain.setBackground(new java.awt.Color(255, 255, 255));
        pnlTrain.setMaximumSize(new java.awt.Dimension(240, 80));
        pnlTrain.setMinimumSize(new java.awt.Dimension(240, 80));
        pnlTrain.setPreferredSize(new java.awt.Dimension(240, 80));

        btnTrain.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnTrain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devfortress/view/resources/icTrain.png"))); // NOI18N
        btnTrain.setText(Constant.TRAIN_BTN);
        btnTrain.setMaximumSize(new java.awt.Dimension(240, 60));
        btnTrain.setMinimumSize(new java.awt.Dimension(240, 60));
        btnTrain.setPreferredSize(new java.awt.Dimension(240, 60));

        javax.swing.GroupLayout pnlTrainLayout = new javax.swing.GroupLayout(pnlTrain);
        pnlTrain.setLayout(pnlTrainLayout);
        pnlTrainLayout.setHorizontalGroup(
            pnlTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTrain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTrainLayout.setVerticalGroup(
            pnlTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrainLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        add(pnlTrain);

        pnlCancel.setMaximumSize(new java.awt.Dimension(127, 58));
        pnlCancel.setMinimumSize(new java.awt.Dimension(127, 58));
        pnlCancel.setPreferredSize(new java.awt.Dimension(127, 58));

        btnCancel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devfortress/view/resources/icCancel.png"))); // NOI18N
        btnCancel.setText(Constant.CLOSE_BTN);
        btnCancel.setMaximumSize(new java.awt.Dimension(127, 48));
        btnCancel.setMinimumSize(new java.awt.Dimension(127, 48));
        btnCancel.setPreferredSize(new java.awt.Dimension(127, 48));

        javax.swing.GroupLayout pnlCancelLayout = new javax.swing.GroupLayout(pnlCancel);
        pnlCancel.setLayout(pnlCancelLayout);
        pnlCancelLayout.setHorizontalGroup(
            pnlCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlCancelLayout.setVerticalGroup(
            pnlCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCancelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(pnlCancel);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGiveFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiveFoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGiveFoodActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGiveBeer;
    private javax.swing.JButton btnGiveFood;
    private javax.swing.JButton btnTrain;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlCancel;
    private javax.swing.JPanel pnlGiveFood;
    private javax.swing.JPanel pnlHaveBeer;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JPanel pnlTrain;
    // End of variables declaration//GEN-END:variables
}
