/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package devfortress.view.dialogs;

import devfortress.model.employee.Employee;
import devfortress.model.facade.Model;
import devfortress.utilities.Constant;
import devfortress.view.editors.TableButtonCellEditor;
import devfortress.view.models.TrainingTableModel;
import devfortress.view.renderers.TableButtonCellRenderer;
import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Sherlock
 */
public class TrainingPanel extends javax.swing.JPanel {

    private ManageEmployeePanel parent;
    private Employee employee;
    private TrainingTableModel tableModel;

    /**
     * Creates new form TrainingPanel.
     *
     * @param parent
     * @param employee
     * @param buttonListener
     */
    public TrainingPanel(JPanel parent, Employee employee,
            ActionListener buttonListener) {
        this.employee = employee;
        initComponents();
        this.parent = (ManageEmployeePanel) parent;
        scpSkills.getViewport().setBackground(Color.white);
        tableModel = (TrainingTableModel) tblSkills.getModel();
        populateData();
        btnClose.addActionListener(buttonListener);
        tblSkills.setDefaultRenderer(JButton.class,
                new TableButtonCellRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        scpSkills = new javax.swing.JScrollPane();
        tblSkills = new javax.swing.JTable();
        pnlClose = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setMaximumSize(new java.awt.Dimension(520, 520));
        setMinimumSize(new java.awt.Dimension(520, 520));
        setPreferredSize(new java.awt.Dimension(520, 520));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        pnlTitle.setBackground(new java.awt.Color(255, 255, 255));
        pnlTitle.setPreferredSize(new java.awt.Dimension(480, 58));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText(employee.getName());

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTitle)
                .addGap(20, 20, 20))
        );

        add(pnlTitle);

        scpSkills.setBackground(new java.awt.Color(255, 255, 255));
        scpSkills.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        tblSkills.setAutoCreateRowSorter(true);
        tblSkills.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tblSkills.setModel(new TrainingTableModel());
        tblSkills.setRowHeight(36);
        tblSkills.setRowSelectionAllowed(false);
        scpSkills.setViewportView(tblSkills);

        add(scpSkills);

        pnlClose.setBackground(new java.awt.Color(255, 255, 255));
        pnlClose.setMaximumSize(new java.awt.Dimension(120, 70));
        pnlClose.setMinimumSize(new java.awt.Dimension(120, 70));
        pnlClose.setPreferredSize(new java.awt.Dimension(120, 70));

        btnClose.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devfortress/view/resources/icCancel.png"))); // NOI18N
        btnClose.setText(Constant.CLOSE_BTN);
        btnClose.setMaximumSize(new java.awt.Dimension(120, 40));
        btnClose.setMinimumSize(new java.awt.Dimension(120, 40));
        btnClose.setPreferredSize(new java.awt.Dimension(120, 40));

        javax.swing.GroupLayout pnlCloseLayout = new javax.swing.GroupLayout(pnlClose);
        pnlClose.setLayout(pnlCloseLayout);
        pnlCloseLayout.setHorizontalGroup(
            pnlCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlCloseLayout.setVerticalGroup(
            pnlCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCloseLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        add(pnlClose);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlClose;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JScrollPane scpSkills;
    private javax.swing.JTable tblSkills;
    // End of variables declaration//GEN-END:variables

    /**
     * Return current employee.
     *
     * @return
     */
    public Employee getEmployee() {
        return employee;
    }
    
    /**
     * Set button cell listener for Project table.
     *
     * @param tableButtonListener
     */
    public void setTableButtonListener(ActionListener tableButtonListener) {
        tblSkills.setDefaultEditor(JButton.class,
                new TableButtonCellEditor(tableButtonListener));
    }

    /**
     * Populate data to table.
     */
    private void populateData() {
        tableModel.setEmployee(employee);
    }

    /**
     * Update skills table.
     */
    public void update() {
        Model model = parent.getModel();
        employee = model.getEmployeeByName(employee.getName());
        populateData();
        parent.update();
    }
}
